# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "bio-bigbio"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pjotr Prins"]
  s.date = "2012-01-30"
  s.description = "Fasta reader, ORF emitter, sequence translation"
  s.email = "pjotr.public01@thebird.nl"
  s.executables = ["getorf", "nt2aa.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/getorf",
    "bin/nt2aa.rb",
    "bio-bigbio.gemspec",
    "doc/bigbio_getorf.wtex",
    "lib/bigbio.rb",
    "lib/bigbio/adapters/translate.rb",
    "lib/bigbio/db/blast.rb",
    "lib/bigbio/db/blast/blastclust.rb",
    "lib/bigbio/db/emitters/fasta_emitter.rb",
    "lib/bigbio/db/emitters/orf_emitter.rb",
    "lib/bigbio/db/fasta.rb",
    "lib/bigbio/db/fasta/fastaindex.rb",
    "lib/bigbio/db/fasta/fastapairedreader.rb",
    "lib/bigbio/db/fasta/fastapairedwriter.rb",
    "lib/bigbio/db/fasta/fastareader.rb",
    "lib/bigbio/db/fasta/fastarecord.rb",
    "lib/bigbio/db/fasta/fastawriter.rb",
    "lib/bigbio/db/fasta/indexer.rb",
    "lib/bigbio/environment.rb",
    "lib/bigbio/sequence/predictorf.rb",
    "lib/bigbio/sequence/translate.rb",
    "spec/emitter_spec.rb",
    "spec/predictorf_spec.rb",
    "test/data/EMBOSS/EGC.1",
    "test/data/fasta/nt.fa",
    "test/doctest/test_fasta.rb",
    "test/doctest/test_frames.rb",
    "test/doctest/test_getorf.rb",
    "test/doctest/test_paired.rb",
    "test/performance/translate_with_biolib.rb",
    "test/performance/translate_with_bioruby.rb"
  ]
  s.homepage = "http://github.com/pjotrp/bigbio"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Low memory sequence emitters"
  s.test_files = [
    "spec/emitter_spec.rb",
    "spec/predictorf_spec.rb",
    "test/doctest/test_fasta.rb",
    "test/doctest/test_frames.rb",
    "test/doctest/test_getorf.rb",
    "test/doctest/test_paired.rb",
    "test/performance/translate_with_biolib.rb",
    "test/performance/translate_with_bioruby.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 1.4.1"])
      s.add_runtime_dependency(%q<bio-logger>, [">= 0.9.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<bio>, [">= 1.4.1"])
      s.add_dependency(%q<bio-logger>, [">= 0.9.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<bio>, [">= 1.4.1"])
    s.add_dependency(%q<bio-logger>, [">= 0.9.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

